### PR TITLE
fix(animator): fix custom animation name handling in 'enter' and 'leave' functions

### LINKED ISSUE #16: Unable to animate 'enter' and 'leave' with custom animation names
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Any

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.2.0

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Executing `this.animator.enter(this.view_self, 'customAnimation');` will always throw an Error due to:

https://github.com/aurelia/animator-velocity/blob/master/src/animator.js#L310-L326

Apparently, there's an unclear section of code in the `_runElementAnimation(element:HTMLElement, name:string, options:any = {}, eventName:string = undefined): Promise<any>` function, which restricts the custom function names to ONLY `:enter` and `:leave`.

**Expected/desired behavior:**
The effect `name` parameter should be checked against `effects` map instead and then should the error be thrown.

### PR DESCRIPTION
**Pull request by Tarpsvo**
Fixes #16

### CODE REVIEW

**Comment by zewa666** [comment]
This makes perfect sense. Now what would be really cool is if we could add unit tests for this section. I think this should be part of https://github.com/aurelia/animator-velocity/blob/master/test/enter.spec.js and or https://github.com/aurelia/animator-velocity/blob/master/test/registerEffect.spec.js.
Maybe you want to give it a try and see how it works out?

**Comment by Tarpsvo** [comment]
Hey. That's cool, I'm interested in looking into how the tests work. I'll add the tests today or tomorrow evening. :)

**Comment by Tarpsvo** [comment]
Added a tiny fix and the tests for this change. Noticed that a lot of the other tests are buggy, I hope it's okay if I submit a PR with reworked tests.

**Comment by EisenbergEffect** [comment]
Feel free to fix up the tests. We haven't had a core contributor working on the animation library in some time. If you have an interest in this area, we could use someone who wanted to own it and keep it fixed up and moving ahead. Think about it :)

**Comment by Tarpsvo** [comment]
That's cool. I can work on this on the side, sure. I fixed most of the test suites on local, but they're dependent on this PR. I'll make another PR with the tests once this one is merged. :)

**Comment by zewa666** [comment]
@Tarpsvo that's really great, the tests are fine as well so I'm looking foward for the upcoming PRs ;)

**Pull request merged**
