### PR TITLE
Updating typings for the animate method indicating that the options a…

### PR DESCRIPTION
**Pull request by Roustalski**
…nd client parameters are optional

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks for the improvement!

**Comment by gheoan** [comment]
@EisenbergEffect, @Roustalski I think this shouldn't have been merged. The d.ts file is modified instead of the .js file

**Comment by EisenbergEffect** [comment]
Doh! How did I not catch that? I can fix up the source.

**Comment by Roustalski** [comment]
:worried: :anguished: Sorry about that!

**Pull request merged**
